global.$ = global.jQuery = require('jquery');
window.Popper = require('popper.js').default;
require('./magic-menu');
require('bootstrap');
require('./bootstrap');
require('./validator.js');
require('./tooltip.js');
require('./date-range.js');
require('./update-toast.js');
require('./order-description-toast.js');
require('./company-grid.js');
require('./order-grid.js');
require('./finance-grid.js');
require('./dashboard.js');
require('./saved-toast');
require('./workspace-save-modal');
require('./workspace-form-project');
